### PR TITLE
Disables video upload

### PR DESCRIPTION
**Pull request by HoffmannP**
This commit introduces a new configuration setting to disable video upload.
It removes both links to uploadvideo.php (former addvideo.php) and prevents the usage of this function if disabled.

### CODE REVIEW

**Comment by HoffmannP** [comment]
@Dagefoerde can I restart the tests as well? Looks to me as if I have the same problem as @aliyevTU.

**Comment by Dagefoerde** [comment]
The problem is the same, but I may have been overconfident as some jobs are failing.  Please wait a bit ;)

**Comment by HoffmannP** [comment]
No problem

**Comment by Dagefoerde** [comment]
It looks better now. Feel free to rebase on top of the current master or to merge the current master into your branch - either way is fine.
Thanks for your work!

**Comment by HoffmannP** [comment]
After all checks have passed (thank you @Dagefoerde ), is there anything I could do to support merging any further? Is complete code coverage mandatory?

**Comment by tobiasreischmann** [comment]
Thanks for your contribution.
However, I don't see the direct advantage of this patch, since both uploads can already be restricted using Moodle capabilities.
Since the plugin already has so many settings, I would like to do not increase this list unnecessarily.
If you want, you could ask in the google group, whether anyone else wants to see this feature integrated, which could convince me to merge it anyways.

**Comment by BerengarWLehr** [comment]
How can you disable the video-upload with Moodle capabilities?

**Comment by tobiasreischmann** [comment]
For each role in you Moodle system you can set, which capabilities this role has and with that, what a user is allowed to do if the role is assigned to the user in a given context.
The relevant capability is block/opencast:addvideo. If you remove this capability from any role in you system, no one (except the admins) are allowed to upload videos.

**Comment by tobiasreischmann** [comment]
See YOURMOODLE/admin/roles/manage.php

**Comment by tobiasreischmann** [comment]
@HoffmannP Did you manage do deactivate the upload using the capabilities?
Do you think that this PR is still needed?

**Comment by HoffmannP** [comment]
I think we don't need this feature anymore so I won't test any further

**Pull request closed without merging**
