### PR TITLE
Add setting to enable / disable the control of ACLs

### PR DESCRIPTION
**Pull request by abias**
This PR is based on PR #129 and has to be merged after #129

With this addition, the admin can configure if the teacher is allowed to control the visibility of an Opencast episode after the episode has been processed.
Additionally, the admin can configure if the episode can be restricted to course groups or not.

Note: 
This change does not have any Behat tests added.
Behat would not only have to upload a video for processing, it would also have to wait until it is really finished processing. This is slightly more complicated as I have time currently.

PS: We have german translations ready for the added / modified strings and are ready to contribute these to AMOS as soon as this patch is merged and published in the plugin repo.

### CODE REVIEW

**Comment by abias** [comment]
I am wondering why Travis job 172.8 failed. This could be a random Travis failure and not related to this patch as the patch succeeded on the same Moodle Version / PHP Version / DB in other jobs.

**Comment by tobiasreischmann** [comment]
Seems random. I restarted the build

**Comment by abias** [comment]
I added another commit as I forgot to update the README

**Comment by abias** [comment]
@tobiasreischmann could you please restart the single failing Travis job so that we could have a green checkmark here :)

**Comment by abias** [comment]
I updated and force-pushed this PR after the review of #129.

**Comment by tobiasreischmann** [comment]
Thanks for yet another nice contribution, Alex :)

**Pull request merged**
