### PR TITLE
Patch for "Invalid signature for signature method HMAC-SHA1" issue

### PR DESCRIPTION
**Pull request by aliyevTU**
Patch for "Invalid signature for signature method HMAC-SHA1" issue
https://github.com/unirz-tu-ilmenau/moodle-block_opencast/issues/144

### CODE REVIEW

**Comment by aliyevTU** [comment]
@tobiasreischmann Could you please assist me with this? Travis builds failed because of node version requirement conflict. Is this something on Travis side, or something on my side that I need to fix to have the PR merged?

**Comment by Dagefoerde** [comment]
Hi, thanks for contributing a patch. Yes, the Travis failure is related to an issue with some Moodle infrastructure changes (specifically, the required version of nodejs was increased). 
I have changed this on the `master` branch just now. I will merge that change to your pull request accordingly.

**Comment by nyok92** [comment]
Hi, i used this patch, installed new plugin but still getting the same error:
HTTP ERROR 401
Problem accessing /lti. Reason:
Invalid signature for signature method HMAC-SHA1

Any news ?

**Comment by tobiasreischmann** [comment]
First, sorry for the delay.
Unfortunately, I can not reproduce this problem.
For two reasons I currently do not want to merge this PR:
1. It does not seem to solve the problem completely. See report from @nyok92
2. Currently the creation of the lti parameters still relies on the oauth-helper in several cases. Changing only this one position where the signature is created seems inconsistent to me.

Could this also be an Opencast problem? Maybe different OC versions handle the signatures differently!?

**Comment by BerengarWLehr** [comment]
I second the patch, it resolve our problem with Opencast @ FSUJena

**Comment by nyok92** [comment]
What version of opencast do you use berangarWLehr ?

**Comment by tobiasreischmann** [comment]
We did not have this problem. However, the patch also did not cause additional problems. Thus, I merged it now. Sorry for the delay

**Pull request merged**
