### PR TITLE
Add setting to hide / show columns on the overview page

### PR DESCRIPTION
**Pull request by abias**
This PR is based on PR #130 and has to be merged after #130

With this addition, the admin can configure if particular columns on the overview page are shown or not.
This patch also moves the "Show publication channel" setting to the newly created proper settings page on-the-fly.

Note:
This change does not have any Behat tests added.
I am sorry for this gap but do not have time to write Behat tests for this feature currently.

PS: We have german translations ready for the added / modified strings and are ready to contribute these to AMOS as soon as this patch is merged and published in the plugin repo.

### CODE REVIEW

**Comment by abias** [comment]
I added another commit as I forgot to update the README

**Comment by abias** [comment]
@tobiasreischmann could you please restart the single failing Travis job so that we could have a green checkmark here :)

**Comment by abias** [comment]
I updated and force-pushed this PR after the review of #129.

**Comment by tobiasreischmann** [comment]
Merged

**Pull request closed without merging**
